Diskriminant/Models/ErrorViewModel.cs
using System;

namespace Diskriminant.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Diskriminant/ViewModels/MovieViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace mvc.ViewModels
{
    public class MovieViewModel
    {
        [Required]
        [MaxLength(54)]
        public string MovieName { get; set; }

        [Required]
        [MaxLength(40)]
        public string Country { get; set; }
        public string Genre { get; set; }
    }
}

Diskriminant/ViewModels/ResultViewModel.cs
namespace mvc.ViewModels
{
    public class ResultViewModel
    {
        public string X1 { get; set; }
        
        public string X2 { get; set; }
        
        public bool HasRoots { get; set; }
    }
}

Diskriminant/ViewModels/SquareRootViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace mvc.ViewModels
{
    public class SquareRootViewModel
    {
        [Required]
        public double A { get; set; }
        
        [Required]
        public double B { get; set; }

        [Required]
        public double C { get; set; }

        public string X1 { get; set; }
        
        public string X2 { get; set; }
        
        public bool HasRoots { get; set; } = false; 
    }
}

Diskriminant/Controllers/MathController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc.ViewModels;

namespace mvc.Controllers
{
    [Route("[controller]")]
    public class MathController : Controller
    {
        private readonly ILogger<MathController> _logger;

        public MathController(ILogger<MathController> logger)
        {   
            _logger = logger;
        }

        [HttpGet("sqrt")]
        public IActionResult SquareRoot()
        {
            return View();
        }

        [HttpPost("sqrt")]
        public IActionResult SquareRoot([FromForm]SquareRootViewModel model)
        {
            var disc = System.Math.Pow(model.B, 2) - 4 * model.A * model.C;

            model.HasRoots = disc >= 0;

            if(disc == 0)
            {
                model.X1 = model.X2 = $"{(-1) * model.B / (model.A * 2)}";
            }
            else if(disc > 0)
            {
                model.X1 = $"{(-1) * model.B + System.Math.Sqrt(disc) / (model.A * 2)}";
                model.X2 = $"{(-1) * model.B - System.Math.Sqrt(disc) / (model.A * 2)}";
            }

            return View(model);
        }

        [HttpGet("result")]
        public IActionResult Result()
        {
            return View();
        }
    }
}

Diskriminant/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc.ViewModels;

namespace mvc.Controllers
{
    [Route("[controller]")]
    public class MovieController : Controller
    {
        private readonly ILogger<MovieController> _logger;

        public MovieController(ILogger<MovieController> logger)
        {
            _logger = logger;
        }

        [HttpGet("movie")]
        public IActionResult Movie()
        {
            return View();
        }

        [HttpPost("movie")]
        public IActionResult Movie([FromForm]MovieViewModel model)
        {
            return View(model);
        }

        [HttpGet("result")]
        public IActionResult Result()
        {
            return View();
        }

    }
}

Diskriminant/Views/Math/Result.cshtml
@model mvc.ViewModels.ResultViewModel

Diskriminant/Views/Math/SquareRoot.cshtml
@model mvc.ViewModels.SquareRootViewModel

<form asp-controller="Math" asp-action="SquareRoot" method="post">
    <div class="row">
        <div class="col-5 mx-auto">
            <input asp-for="A" style="max-width: 30px;" placeholder="A"/> X&#178; + 
            <input asp-for="B" style="max-width: 30px;" placeholder="B"/> X + 
            <input asp-for="C" style="max-width: 30px;" placeholder="C"/> = 0
            <h5 class="mt-3"><button class="btn btn-primary" type="submit">Solve</button></h5>
        </div>
    </div>

</form>

@if(Model != null)
{

    @if(Model.HasRoots)
    {
        if(!string.IsNullOrWhiteSpace(Model.X1) && Model.X1 == Model.X2)
        {
            <p>X1, X2 = @Model.X1</p>
        }
        else
        {
            <p>X1 = @Model.X1</p>
            <p>X2 = @Model.X2</p>
        }
    }
    else
    {
        <p>Javobi yo'q!</p>
    }
}

Diskriminant/Views/Movie/Movie.cshtml
@model mvc.ViewModels.MovieViewModel

<form asp-controller="Movie" asp-action="Movie" method="post">
    <div class="form-horizontal">
        <div class="col-md-10">
            <div>
                <p> Movie Name: <input asp-for="MovieName" style="max-width: 200px;" /> </p>
            </div>

            <div>
                <p> Company name: <input asp-for="Country" style="max-width: 200px;"/> </p>
            </div>

            <div>
                <p> Genre: <input asp-for="Genre" style="max-width: 200px;"/> </p>
            </div>
            <h5 class="mt-3"><button class="btn btn-primary" type="submit">Purchase</button></h5>
        </div>
    </div>
</form>

@* @{
    ViewBag.Title = "www.compilemode.com";
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <label class="col-md-2 control-label">Select Country</label>
            <div class="col-md-10">
                @Html.DropDownList("CountryList",new SelectList(ViewBag.CountryList),new {@class = "form-control" })
            </div>
        </div>
    </div>
} *@

Diskriminant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diskriminant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Diskriminant</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Diskriminant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>